"""
Central database for roofing product keywords and pricing.
Auto-generated from price_list.xlsx by excel_to_database.py.
Referenced by file_extractor.py and buildingfootprintquery.py.
"""

# ---------------------------------------------------------------------------
# Pricing per unit – aggregated from price_list.xlsx
# Each entry: key → {avg, min, max, count, unit, sample_descriptions}
# ---------------------------------------------------------------------------
PRICING = {
    "DensDeck_Coverboard": {
        "canonical_name": "DensDeck Coverboard",
        "category": "Coverboard",
        "avg_price": 33.52,
        "min_price": 29.00,
        "max_price": 37.40,
        "count": 4,
        "unit": "SHT",
        "sample_descriptions": ["DENSDECK PRIME ROOF BOARD 12inX4ftX8ft", "1/4\"X4'X8' Densdeck Primed", "1/2\"X4'X8' Densdeck Primed"],
    },
    "Gypsum_Fiber_Coverboard": {
        "canonical_name": "Gypsum Fiber Coverboard",
        "category": "Coverboard",
        "avg_price": 29.62,
        "min_price": 15.77,
        "max_price": 34.00,
        "count": 13,
        "unit": "Sheet",
        "sample_descriptions": ["SECUROCK GYPSUM FBR 3/8inX4 X8", "SECUROCK GYPSUM FBR 1/2inX4 X8", "SECUROCK GYPSUM FIBER ROOF BOARD 12inX4ftX8ft (061052)"],
    },
    "Drainage_Board": {
        "canonical_name": "Drainage Board",
        "category": "Drainage",
        "avg_price": 410.53,
        "min_price": 215.70,
        "max_price": 601.92,
        "count": 7,
        "unit": "Roll",
        "sample_descriptions": ["SOPRADRAIN 15-G 6ftX50ft", "MIRADRAIN 9000 DRAIN BOARD 6X50'", "SOPRADRAIN ECO 5 6ftX65.6ft"],
    },
    "Gutter_Downpipe": {
        "canonical_name": "Gutter / Downpipe",
        "category": "Drainage",
        "avg_price": 13.60,
        "min_price": 1.25,
        "max_price": 20.55,
        "count": 3,
        "unit": "Piece",
        "sample_descriptions": ["Downpipe & Elbow Package", "Gutter and Downpipe Package", "Downpipe Small Square"],
    },
    "Roof_Drain": {
        "canonical_name": "Roof Drain",
        "category": "Drainage",
        "avg_price": 181.77,
        "min_price": 4.95,
        "max_price": 381.00,
        "count": 26,
        "unit": "EA",
        "sample_descriptions": ["Thaler Aluminum Roof Drain -SS 1 1/4", "Bolts Roof Drain Ancon FC-2", "3\" MJ Large Drain Body"],
    },
    "Scupper": {
        "canonical_name": "Scupper",
        "category": "Drainage",
        "avg_price": 74.83,
        "min_price": 30.48,
        "max_price": 206.00,
        "count": 5,
        "unit": "EA",
        "sample_descriptions": ["COPPER SCUPPER 2\"", "COPPER SCUPPER 3\"", "Scupper 6in Closed"],
    },
    "Clips": {
        "canonical_name": "Clips",
        "category": "Fasteners & Hardware",
        "avg_price": 10.19,
        "min_price": 0.50,
        "max_price": 48.06,
        "count": 27,
        "unit": "Piece",
        "sample_descriptions": ["Clip Base Various", "Fixed Clip various - Floating Clip", "LKME ULTIMATE THERMAL CLIP 1.5\""],
    },
    "Fasteners": {
        "canonical_name": "Fasteners",
        "category": "Fasteners & Hardware",
        "avg_price": 447.76,
        "min_price": 113.50,
        "max_price": 1648.20,
        "count": 81,
        "unit": "PL",
        "sample_descriptions": ["Fastener #14 Heavy Duty Drill Point 1.5\" (1M)", "Fastener #14 Heavy Duty Drill Point 2.0\" (1M)", "Fastener #14 Heavy Duty Drill Point 2.5\" (1M)"],
    },
    "Insulation_Plates": {
        "canonical_name": "Insulation Plates",
        "category": "Fasteners & Hardware",
        "avg_price": 269.38,
        "min_price": 242.10,
        "max_price": 314.40,
        "count": 4,
        "unit": "PL",
        "sample_descriptions": ["Plate Barbed Seam 2.0\" MPB-2000 (1M)", "Plate Insulation MP-3000 3.0\" (1M)", "Plate Metal Seam 2.0\" MP-2000 (1M)"],
    },
    "Nails_Staples": {
        "canonical_name": "Nails / Staples",
        "category": "Fasteners & Hardware",
        "avg_price": 29.75,
        "min_price": 0.80,
        "max_price": 91.72,
        "count": 12,
        "unit": "Box",
        "sample_descriptions": ["Roofing Nail various", "Staple Hammer", "NAIL ROUND TOP 1\""],
    },
    "Roof_Anchor": {
        "canonical_name": "Roof Anchor",
        "category": "Fasteners & Hardware",
        "avg_price": 16.99,
        "min_price": 16.99,
        "max_price": 16.99,
        "count": 1,
        "unit": "Box",
        "sample_descriptions": ["Anchor Roof Reusable Hinged c/w Nails"],
    },
    "Screws": {
        "canonical_name": "Screws",
        "category": "Fasteners & Hardware",
        "avg_price": 39.96,
        "min_price": 2.29,
        "max_price": 113.31,
        "count": 8,
        "unit": "Box",
        "sample_descriptions": ["Screw Deck Zinc  various", "#12 dekfast Screw - 2''", "Screw Multipurpose 8x1.5'' (6500) ZN"],
    },
    "Batt_Insulation": {
        "canonical_name": "Batt Insulation",
        "category": "Insulation",
        "avg_price": 91.90,
        "min_price": 46.87,
        "max_price": 149.75,
        "count": 4,
        "unit": "Bdl",
        "sample_descriptions": ["Comfortbatt R24", "Comfortbatt R14 3.5X23", "Comfortbatt R22 5x23"],
    },
    "Fiberboard_Insulation": {
        "canonical_name": "Fiberboard Insulation",
        "category": "Insulation",
        "avg_price": 24.85,
        "min_price": 8.94,
        "max_price": 76.50,
        "count": 11,
        "unit": "SH",
        "sample_descriptions": ["MSL Fiberboard Std.Ctd 1/2in 4 X 4 Sheet", "Fiberboard Std.Ctd 1/2in 2ft X 4ft", "1/2\"X2'X4' Standard Coated Fiberboard (96SF)"],
    },
    "Polyisocyanurate_ISO_Insulation": {
        "canonical_name": "Polyisocyanurate (ISO) Insulation",
        "category": "Insulation",
        "avg_price": 43.62,
        "min_price": 13.67,
        "max_price": 185.00,
        "count": 31,
        "unit": "Sheet",
        "sample_descriptions": ["SOPRA-ISO PLUS- 2.5inX4 X4-", "SOPRA-ISO 2.5inX4 X4", "SOPRA-ISO PLUS HD 1/2inX4ftX8ft"],
    },
    "XPS_Insulation": {
        "canonical_name": "XPS Insulation",
        "category": "Insulation",
        "avg_price": 35.53,
        "min_price": 14.60,
        "max_price": 58.40,
        "count": 8,
        "unit": "Sheet",
        "sample_descriptions": ["SOPRA-XPS 35 SL 2inX2ftX8ft", "SOPRA-XPS 35 SL 3inX2ftX8ft", "SOPRA-XPS 35 SL 4inX2ftX8ft"],
    },
    "Base_Membrane": {
        "canonical_name": "Base Membrane",
        "category": "Membranes",
        "avg_price": 193.85,
        "min_price": 62.75,
        "max_price": 324.95,
        "count": 2,
        "unit": "RL",
        "sample_descriptions": ["SOP VAPOR R BASE SHEET 45\" 5Sq", "Elastoflex WC 30SBS Base Sheet Poly"],
    },
    "Cap_Membrane": {
        "canonical_name": "Cap Membrane",
        "category": "Membranes",
        "avg_price": 216.95,
        "min_price": 216.95,
        "max_price": 216.95,
        "count": 1,
        "unit": "Roll",
        "sample_descriptions": ["Paradiene 30FR TG Cap Sheet"],
    },
    "EPDM_Accessory": {
        "canonical_name": "EPDM Accessory",
        "category": "Membranes",
        "avg_price": 398.99,
        "min_price": 0.62,
        "max_price": 4880.00,
        "count": 41,
        "unit": "Roll",
        "sample_descriptions": ["EPDM Elastoform 9x50", "EPDM P/S OVERLAYMENT STRIP 9inX100ft", "EPDM PS Elastoform 6x100"],
    },
    "EPDM_Membrane": {
        "canonical_name": "EPDM Membrane",
        "category": "Membranes",
        "avg_price": 1119.86,
        "min_price": 571.90,
        "max_price": 1530.00,
        "count": 5,
        "unit": "roll",
        "sample_descriptions": ["Carlisle Sure-Seal 60 mil non - reinforced EPDM 10'", "Carlilse Sure-Seal  60 mil Reinforced  EPDM 10'", "Carlilse Sure-Seal  45 mil Reinforced  EPDM 10'"],
    },
    "PVC_Membrane": {
        "canonical_name": "PVC Membrane",
        "category": "Membranes",
        "avg_price": 810.07,
        "min_price": 262.50,
        "max_price": 1674.20,
        "count": 3,
        "unit": "Roll",
        "sample_descriptions": ["SENTINEL P150 60MIL PVC MEMBRANE", "PVC Membrane Cleaner 5 Gallon", "PVC membrane cleaner"],
    },
    "SBS_Membrane": {
        "canonical_name": "SBS Membrane",
        "category": "Membranes",
        "avg_price": 298.00,
        "min_price": 146.00,
        "max_price": 450.00,
        "count": 2,
        "unit": "Roll",
        "sample_descriptions": ["Tradesman SBS Glass SA Base", "POWERPLY SBS BASE HW"],
    },
    "TPO_Accessory": {
        "canonical_name": "TPO Accessory",
        "category": "Membranes",
        "avg_price": 499.33,
        "min_price": 0.98,
        "max_price": 2699.00,
        "count": 56,
        "unit": "Pce",
        "sample_descriptions": ["TPO inside corners", "TPO molded pipe boots     3/4'' - 8''", "Firestone TPO White 060 10ft x 100ft"],
    },
    "TPO_Membrane": {
        "canonical_name": "TPO Membrane",
        "category": "Membranes",
        "avg_price": 2865.53,
        "min_price": 750.00,
        "max_price": 7805.00,
        "count": 57,
        "unit": "SqFt",
        "sample_descriptions": [".060 mil Sure-weld TPO Membrane 10'", "TREMPLY TPO 45 MIL  120\" X 100'", "TREMPLY TPO FB 45 MIL  120\" X 100'"],
    },
    "Vapour_Barrier_Membrane": {
        "canonical_name": "Vapour Barrier Membrane",
        "category": "Membranes",
        "avg_price": 173.66,
        "min_price": 14.97,
        "max_price": 515.00,
        "count": 14,
        "unit": "Roll",
        "sample_descriptions": ["Membrane 3015 6\"-75' 3/3 Vapour Barrier", "IKO M.V.P. Vapor Barrier 1X32", "IKO M.V.P. Sand Vapor Barrier (36\"X80')"],
    },
    "Coated_Metal_Sheet": {
        "canonical_name": "Coated Metal Sheet",
        "category": "Metal Flashings & Accessories",
        "avg_price": 583.11,
        "min_price": 371.90,
        "max_price": 741.00,
        "count": 5,
        "unit": "Sheet",
        "sample_descriptions": ["TPO COATED METAL 4'X10' GRAY", "Plate Metal Barbed Seam 2.4\" (1M)", "Carlisle TPO Coated Metal 4'X10'"],
    },
    "Drip_Edge": {
        "canonical_name": "Drip Edge",
        "category": "Metal Flashings & Accessories",
        "avg_price": 6.85,
        "min_price": 6.70,
        "max_price": 6.99,
        "count": 2,
        "unit": "EA",
        "sample_descriptions": ["Drip Edge 10ft", "Reversible Drip Edge 10'"],
    },
    "Flashing_General": {
        "canonical_name": "Flashing (General)",
        "category": "Metal Flashings & Accessories",
        "avg_price": 174.46,
        "min_price": 0.59,
        "max_price": 1024.00,
        "count": 45,
        "unit": "18",
        "sample_descriptions": ["Alsan RS 230 Flash Winter 7032 (3)", "Armourbond Flash  2.5mm x 15m", "Alsan RS 230 Flash Summer  7032 (3)"],
    },
    "Metal_Panel": {
        "canonical_name": "Metal Panel",
        "category": "Metal Flashings & Accessories",
        "avg_price": 10.95,
        "min_price": 3.70,
        "max_price": 55.00,
        "count": 9,
        "unit": "lin foot",
        "sample_descriptions": ["WF-ALLCLAD PANEL 24GA Tan", "24Ga Panel", "24 GA 1.5\" RIB x 12.25\" Panel"],
    },
    "Standing_Seam_Metal": {
        "canonical_name": "Standing Seam Metal",
        "category": "Metal Flashings & Accessories",
        "avg_price": 6.34,
        "min_price": 1.20,
        "max_price": 16.99,
        "count": 4,
        "unit": "Piece",
        "sample_descriptions": ["24ga 2'' Standing Seam - 18\":40yr SMP Charcoal", "Standing Seam 3/4\" Clip", "Standing Seam 1 1/2\" Clip"],
    },
    "Coating_Paint": {
        "canonical_name": "Coating / Paint",
        "category": "Miscellaneous",
        "avg_price": 1088.17,
        "min_price": 0.77,
        "max_price": 6409.00,
        "count": 40,
        "unit": "Pail",
        "sample_descriptions": ["Paint various", "Roofcraft Roof and Found Coating 20L", "RESISTO FIBROUS COATING (18.9L)"],
    },
    "Equipment_Torch": {
        "canonical_name": "Equipment / Torch",
        "category": "Miscellaneous",
        "avg_price": 220.19,
        "min_price": 24.85,
        "max_price": 591.45,
        "count": 16,
        "unit": "Roll",
        "sample_descriptions": ["HPR® Torch Base", "Propane Tank various", "Sopraply Torch Base 520 1x10"],
    },
    "Fleece_Reinforcement_Fabric": {
        "canonical_name": "Fleece Reinforcement Fabric",
        "category": "Miscellaneous",
        "avg_price": 1192.69,
        "min_price": 53.15,
        "max_price": 4198.00,
        "count": 22,
        "unit": "Roll",
        "sample_descriptions": ["Alsan 4'' x 165' Fleece", "Alsan RS Fleece 10.3'' x 165' Fleece", "Alsan RS 41'' x 165' Fleece"],
    },
    "Tape": {
        "canonical_name": "Tape",
        "category": "Miscellaneous",
        "avg_price": 425.57,
        "min_price": 0.59,
        "max_price": 2940.00,
        "count": 47,
        "unit": "Piece",
        "sample_descriptions": ["Tape Masking", "Tape measure", "Tape Caution"],
    },
    "Walkway_Pads": {
        "canonical_name": "Walkway Pads",
        "category": "Pavers & Walkways",
        "avg_price": 590.10,
        "min_price": 134.00,
        "max_price": 1048.50,
        "count": 3,
        "unit": "RL",
        "sample_descriptions": ["IKO InnoviTPO Walkway Pad White", "Firestone Premium Walkway Pad", "PEBBLE TREAD WALKPAD 3' X 4' X 3/4\""],
    },
    "Adhesive": {
        "canonical_name": "Adhesive",
        "category": "Sealants & Adhesives",
        "avg_price": 735.19,
        "min_price": 5.02,
        "max_price": 11852.00,
        "count": 91,
        "unit": "PL",
        "sample_descriptions": ["IKO SAM Adhesive 5GAL", "Duotack Foamable Adhesive", "SENTINEL S BONDING ADHESIVE-5 GAL"],
    },
    "Adhesive_Elastocol": {
        "canonical_name": "Adhesive (Elastocol)",
        "category": "Sealants & Adhesives",
        "avg_price": 99.74,
        "min_price": 0.00,
        "max_price": 188.39,
        "count": 8,
        "unit": "36",
        "sample_descriptions": ["Elastocol Stick 19L", "Elastocol 500 19L", "ELASTOCOL 500 (V2024) 19L"],
    },
    "Mastic": {
        "canonical_name": "Mastic",
        "category": "Sealants & Adhesives",
        "avg_price": 359.30,
        "min_price": 5.55,
        "max_price": 3219.00,
        "count": 50,
        "unit": "Piece",
        "sample_descriptions": ["SOPRAMASTIC BLOCK 5inRND CURB", "Sopramastic PF 2L", "Sopramastic SP2 300ml"],
    },
    "Primer": {
        "canonical_name": "Primer",
        "category": "Sealants & Adhesives",
        "avg_price": 282.83,
        "min_price": 9.10,
        "max_price": 3145.00,
        "count": 76,
        "unit": "Pail",
        "sample_descriptions": ["EPDM HP-250 primer", "BLUESKIN PRIMER/ADHESIVE 17L 36/PLT", "Primer CCW-702 5 Gal"],
    },
    "Sealant_General": {
        "canonical_name": "Sealant (General)",
        "category": "Sealants & Adhesives",
        "avg_price": 29.86,
        "min_price": 5.99,
        "max_price": 329.00,
        "count": 25,
        "unit": "Tube",
        "sample_descriptions": ["SOPRASEAL SEALANT", "Sealant Henry 925 BES", "Lap Sealant"],
    },
    "Gooseneck_Vent": {
        "canonical_name": "Gooseneck Vent",
        "category": "Vents & Penetrations",
        "avg_price": 53.21,
        "min_price": 35.65,
        "max_price": 69.55,
        "count": 9,
        "unit": "Piece",
        "sample_descriptions": ["6x6 Gooseneck Vent", "Gooseneck Square Soldered 8 x 8", "8x8 Gooseneck Vents"],
    },
    "Pipe_Boot_Seal": {
        "canonical_name": "Pipe Boot / Seal",
        "category": "Vents & Penetrations",
        "avg_price": 50.48,
        "min_price": 43.50,
        "max_price": 57.45,
        "count": 2,
        "unit": "EA",
        "sample_descriptions": ["CAR PS EPDM M PIPE SEAL 1-6\"", "CAR TPO MLD PIPE SEAL 3/4-8\" WH"],
    },
    "Plumbing_Vent": {
        "canonical_name": "Plumbing Vent",
        "category": "Vents & Penetrations",
        "avg_price": 21.87,
        "min_price": 21.38,
        "max_price": 22.35,
        "count": 2,
        "unit": "Piece",
        "sample_descriptions": ["4'' Plumbing Vent", "3'' Plumbing Vent"],
    },
    "Roof_Hatch": {
        "canonical_name": "Roof Hatch",
        "category": "Vents & Penetrations",
        "avg_price": 1822.12,
        "min_price": 329.95,
        "max_price": 3622.25,
        "count": 12,
        "unit": "Piece",
        "sample_descriptions": ["Bilco NB-20 Hatch 30x54", "Bilco Roof Hatch S-20 36in x30in", "Bilco Roof Hatch S-20 36in x30in"],
    },
    "Vent_Cap": {
        "canonical_name": "Vent Cap",
        "category": "Vents & Penetrations",
        "avg_price": 57.75,
        "min_price": 1.70,
        "max_price": 217.24,
        "count": 15,
        "unit": "Piece",
        "sample_descriptions": ["5'' Vent Cap", "6'' Vent Cap", "TP-250 Prevent Cap 4.0mm (1X8M)"],
    },
    "Plywood_Sheathing": {
        "canonical_name": "Plywood Sheathing",
        "category": "Wood & Sheathing",
        "avg_price": 48.74,
        "min_price": 15.45,
        "max_price": 103.63,
        "count": 5,
        "unit": "Piece",
        "sample_descriptions": ["4X8X3/4 STD FIR SHEATHING", "4X8X1/2 STD FIR SHEATHING", "4X8X3/4 PT BRN SHEATHING"],
    },
    "Wood_Blocking_Lumber": {
        "canonical_name": "Wood Blocking / Lumber",
        "category": "Wood & Sheathing",
        "avg_price": 16.59,
        "min_price": 2.36,
        "max_price": 51.59,
        "count": 19,
        "unit": "Piece",
        "sample_descriptions": ["SPF 2x4x8", "SPF 2x4x10", "SPF 2x6x8"],
    },
}

# ---------------------------------------------------------------------------
# Product keyword database – preserved from original database.py
# Each entry: regex pattern → canonical product name
# ---------------------------------------------------------------------------
PRODUCT_KEYWORDS: dict[str, dict[str, str]] = {
    "Membranes": {
        r"granule\s+surfaced\s+thermofusible\s+cap\s+membrane": "Granule Surfaced Thermofusible Cap Membrane",
        r"cap\s+membrane\s+flash": "Cap Membrane Flashings",
        r"base\s+membrane\s+flash": "Base Membrane Flashings",
        r"vapou?r\s+barrier\s+membrane": "Vapour Barrier Membrane",
        r"liquid\s+membrane\s+flash": "Liquid Membrane Flashing",
        r"sbs\s+membrane": "SBS Membrane",
        r"coverboard\s+with\s+factory\s+laminated\s+base\s+membrane": "Coverboard with Factory Laminated Base Membrane",
        r"membrane\s+pipe\s+seal": "Membrane Pipe Seal",
        r"sacrificial\s+cap\s+membrane": "Sacrificial Cap Membrane (slip sheet)",
        # Soprema SBS products (Div 07 52 01)
        r"sopraply\s+traffic\s+cap": "Sopraply Traffic Cap (SBS Cap Sheet)",
        r"sopraply\s+base\s+520": "Sopraply Base 520 (SBS Base Sheet)",
        r"sopraply\s+stick\s+duo": "Sopraply Stick Duo (Self-Adhered Base)",
        r"soprasmart\s+board": "Soprasmart Board 2:1 (Factory Laminated ISO+Base)",
        r"modified\s+bitumen\s+membrane": "Modified Bitumen Membrane",
        r"2[- ]ply\s+sbs": "2-Ply SBS Membrane System",
        r"inverted.*membrane\s+roof": "Inverted Membrane Roofing",
    },
    "Insulation": {
        r"polyisocyanurate\s+insulation": "Polyisocyanurate Insulation",
        r"fibe?r\s*board\s+insulation": "Fiberboard Insulation",
        r"tapered\s+expanded\s+polystyrene\s+insulation": "Tapered Expanded Polystyrene (EPS) Insulation",
        r"tapered\s+insulation\s+sump": "Tapered Insulation Sump",
        r"xps\s+insulation": "XPS Insulation",
        r"mineral\s+wool\s+insulation": "Mineral Wool Insulation",
        r"spray\s+foam": "Spray Foam Insulation",
        r"drain\s+bowl/?pipe\s+insulation": "Drain Bowl/Pipe Insulation",
        r"type\s+iv\s+xps": "Type IV XPS Insulation",
        # Soprema specific (Div 07 52 01)
        r"sopra-?xps\s+40": "Sopra-XPS 40 Type 4 (Inverted Insulation)",
        r"type\s+4\s+xps": "Type 4 XPS Insulation",
        r"tapered\s+polyisocyanurate": "Tapered Polyisocyanurate Insulation",
    },
    "Coverboard": {
        r"\d+\s*mm\s+coverboard": "Coverboard",
    },
    "Metal Flashings & Accessories": {
        r"metal\s+cap\s+flash": "Metal Cap Flashings",
        r"metal\s+scupper\s+flash": "Metal Scupper Flashings",
        r"metal\s+skirt\s+flash": "Metal Skirt Flashings",
        r"metal\s+counter\s+flash": "Metal Counter Flashings",
        r"metal\s+base\s+flash": "Metal Base Flashings",
        r"metal\s+gooseneck\s+flash": "Metal Gooseneck Flashings",
        r"metal\s+brakeshape": "Metal Brakeshape",
        r"metal\s+debris\s+screen": "Metal Debris Screen",
        r"standing\s+seam": "Standing Seam Metal",
        r"s-lock": "S-Lock Joint",
        r"hem\s+edge": "Hem Edge Detail",
    },
    "Wood & Sheathing": {
        r"plywood\s+sheathing": "Plywood Sheathing",
        r"back-?sloped.*plywood\s+sheathing": "Back-Sloped Plywood Sheathing",
        r"wood\s+blocking": "Wood Blocking",
    },
    "Drainage": {
        r"drain\s+clamping\s+ring": "Drain Clamping Ring",
        r"drain\s+bowl": "Drain Bowl",
        r"sump\s+receiver\s+pan": "Sump Receiver Pan",
        r"lead\s+flash": "Lead Flashings",
        r"overflow\s+scupper": "Overflow Scupper",
        r"roof\s+drain": "Roof Drain",
        r"scupper\s+drain": "Scupper Drain",
        # Soprema / inverted roof (Div 07 52 01)
        r"sopradrain": "Sopradrain EcoVent (Drainage Board)",
        r"filter\s+fabric": "Filter Fabric",
        r"drainage\s+board": "Drainage Board",
    },
    "Fasteners & Hardware": {
        r"pan\s+head\s+(fastener|screw)": "Pan Head Fasteners/Screws",
        r"hex\s+head\s+(fastener|screw)": "Hex Head Fasteners/Screws",
        r"wood\s+screw": "Wood Screws",
        r"neoprene\s+washer": "Neoprene Washers",
        r"\d+\s*mm\s+clips?": "Metal Clips",
        r"roof\s+anchor": "Roof Anchor",
    },
    "Sealants & Adhesives": {
        r"asphaltic\s+primer": "Asphaltic Primer",
        r"mastic": "Mastic",
        r"urethane\s+sealant": "Urethane Sealant",
        r"exterior\s+grade\s+sealant": "Exterior Grade Sealant",
        r"membrane\s+compatible\s+sealant": "Membrane Compatible Sealant",
        r"adhesive\s+ribbon": "Adhesive Ribbon",
        r"(?<!urethane\s)(?<!exterior\sgrade\s)(?<!membrane\scompatible\s)sealant": "Sealant (General)",
        # Soprema / Div 07 specific
        r"dymonic\s+100": "Dymonic 100 (Polyurethane Sealant)",
        r"masterseal\s+np[\s-]?1": "MasterSeal NP1 (Polyurethane Sealant)",
        r"elastocol": "Elastocol Adhesive",
        r"sopramastic": "Sopramastic",
        r"polyurethane\s+sealant": "Polyurethane Sealant",
    },
    "Pavers & Walkways": {
        r"concrete\s+paver": "Concrete Pavers",
        r"\d+\s*mm\s*x\s*\d+\s*mm\s*x\s*\d+\s*mm\s+paver": "Concrete Pavers (sized)",
    },
    "Vents & Penetrations": {
        r"spun\s+aluminum\s+vent\s+flash": "Spun Aluminum Vent Flashing",
        r"abs\s+pipe": "ABS Pipe",
        r"vent\s+extension\s+pipe": "Vent Extension Pipe",
        r"vent\s+cap": "Vent Cap",
        r"roof\s+hatch": "Roof Hatch",
        r"plumbing\s+vent": "Plumbing Vent",
        r"gooseneck": "Gooseneck Vent",
    },
    "Miscellaneous": {
        r"foam\s+gasket": "Foam Gasket",
        r"polyethylene\s+film": "Polyethylene Film",
        r"tremclad\s+paint": "Tremclad Paint",
        r"fleece\s+reinforcement\s+fabric": "Fleece Reinforcement Fabric",
        r"gypsum\s+auxiliary\s+leveling\s+surface": "Gypsum Auxiliary Leveling Surface",
        r"steel\s+deck": "Steel Deck",
        r"c-?ports?": "C-Port Pipe Supports",
        r"sleepers?": "Sleepers",
        # Inverted roof / ballast
        r"gravel\s+ballast": "Gravel Ballast",
        r"paver\s+pedestal": "Paver Pedestals",
        r"mammouth\s+platinum": "Soprema Mammouth Platinum Warranty",
    },
}

# ---------------------------------------------------------------------------
# NEW product categories discovered from Excel (heuristic match)
# Review and merge into PRODUCT_KEYWORDS above as needed.
# ---------------------------------------------------------------------------
NEW_KEYWORDS_CANDIDATES: dict[str, list[str]] = {
    "Coverboard": [
        "DensDeck Coverboard",
        "Gypsum Fiber Coverboard",
    ],
    "Drainage": [
        "Drainage Board",
        "Gutter / Downpipe",
        "Scupper",
    ],
    "Fasteners & Hardware": [
        "Clips",
        "Fasteners",
        "Insulation Plates",
        "Nails / Staples",
        "Screws",
    ],
    "Insulation": [
        "Batt Insulation",
        "Polyisocyanurate (ISO) Insulation",
    ],
    "Membranes": [
        "Base Membrane",
        "Cap Membrane",
        "EPDM Accessory",
        "EPDM Membrane",
        "PVC Membrane",
        "TPO Accessory",
        "TPO Membrane",
    ],
    "Metal Flashings & Accessories": [
        "Coated Metal Sheet",
        "Drip Edge",
        "Flashing (General)",
        "Metal Panel",
    ],
    "Miscellaneous": [
        "Coating / Paint",
        "Equipment / Torch",
        "Tape",
    ],
    "Pavers & Walkways": [
        "Walkway Pads",
    ],
    "Sealants & Adhesives": [
        "Adhesive",
        "Adhesive (Elastocol)",
        "Primer",
    ],
    "Vents & Penetrations": [
        "Pipe Boot / Seal",
    ],
    "Wood & Sheathing": [
        "Wood Blocking / Lumber",
    ],
}